from typing import Optional
from sqlmodel import Field, SQLModel
from datetime import datetime, timezone

class User(SQLModel, table=True):
    """
    Stores user information. For Supabase Auth, the 'id' will be the 
    UUID string generated by Supabase.
    """
    id: str = Field(default=None, primary_key=True)
    email: str = Field(unique=True, index=True)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class ImageRecord(SQLModel, table=True):
    """
    Stores the history of images uploaded and modified by the user.
    """
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: str = Field(foreign_key="user.id")
    
    # Track the original filename and where it's stored (we can use local or cloud storage later)
    filename: str
    
    # Store the metadata that was manipulated
    original_lat: Optional[float] = None
    original_lon: Optional[float] = None
    modified_lat: Optional[float] = None
    modified_lon: Optional[float] = None
    
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))